### ISSUE TITLE
about the package

### ISSUE THREAD

**Issue by OoviceroO** [hrnr/map-merge#1]
Hi 
I have download the package , but when i catkin_make , some errors occur . Could you help me to slove these errors?
![2018-05-09 15-09-51](https://user-images.githubusercontent.com/33340115/39800651-16e2151e-539b-11e8-9513-16c21b0ba633.png)

**Comment by hrnr** [comment]
The package needs pcl >= 1.8. I'm aiming to release it for ROS melodic. It works also with ROS lunar, but only on debian which has pcl 1.8. To avoid this confusion, I'm planning to only support ROS melodic and beyond.

**Comment by OoviceroO** [comment]
Thanks for your answers.

**Comment by hrnr** [comment]
The package has been released to ROS melodic.
